-- Role: elr-ro

-- DROP ROLE "elr-ro";

CREATE ROLE "elr-ro"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- Role: elr-rw

-- DROP ROLE "elr-rw";

CREATE ROLE "elr-rw"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- Role: elr-su

-- DROP ROLE "elr-su";

CREATE ROLE "elr-su"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

  
-- Role: droolsuser

-- DROP ROLE droolsuser;

CREATE ROLE droolsuser LOGIN PASSWORD 'droolspass'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "elr-rw" TO droolsuser;


-- Role: dcpadmin

-- DROP ROLE dcpadmin;

CREATE ROLE dcpadmin LOGIN PASSWORD 'droolspass'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;