# Source: kratos/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: php-ui
  namespace: default
  labels:
    app.kubernetes.io/name: php-ui
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: php-ui
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: php-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-ui
  namespace: default
  labels:
    app.kubernetes.io/name: php-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: php-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-ui
    spec:
      containers:
        - name: php-ui
          image: php-auth
          envs:
          - name: ORY_SDK_URL
            value: http://test-kratos-private:4433/
          # - name: ORY_SDK_URL
          #   value: http://ory.test.info/.ory/kratos/private
          imagePullPolicy: Always
          ports:
            - name: php-ui
              containerPort: 80
              protocol: TCP
