apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app.kubernetes.io/name: emsa-db
  name: emsa-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emsa-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: emsa-db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=1000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emsa-db-secrets
                  key: EMSA_POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: emsa-db-secrets
                  key: EMSA_POSTGRES_USER
          image: emsa-db
          name: emsa-db
          ports:
            - containerPort: 5432
      restartPolicy: Always
